"""Independently reviewed early survival pieces and conditional set combinations."""

from dataclasses import dataclass, replace

from dirty_equals import Contains, IsPartialDict

from tests.pricing.knowledge.assessment.item_bank.models import Case, Item


@dataclass(frozen=True)
class Review:
    name: str
    base: str
    level: int
    strength: int
    stats: tuple
    snippets: tuple
    combination: str | None = None
    trade: str = 'low'
    leveling: str = 'med'
    player_class: str = 'Amazon'


# These are literal native requirements/modifiers and independently reviewed uses,
# not expectations generated by the production recommendations loader.
REVIEWS = (
    Review("Berserker's Headgear", 'Helm', 3, 26, ((39, 0, 25),), ('Fire Resist +25%',)),
    Review("Cow King's Hide", 'Studded Leather', 18, 27, ((7, 0, 30 * 256), (16, 0, 60)), (), 'cow'),
    Review(
        "Cow King's Hooves",
        'Heavy Boots',
        13,
        18,
        ((96, 0, 30), (2, 0, 20), (80, 0, 25)),
        ('30% Faster Run/Walk',),
        'cow',
    ),
    Review("Cow King's Horns", 'War Hat', 25, 20, ((78, 0, 10),), (), 'cow'),
    Review("Hsarus' Iron Fist", 'Buckler', 3, 12, ((0, 0, 10), (34, 0, 2)), (), "Hsarus' Defense"),
    Review(
        "Hsarus' Iron Heel", 'Chain Boots', 3, 30, ((39, 0, 25), (96, 0, 20)), ('20% Faster Run/Walk',), 'hsarus-boots'
    ),
    Review("Hsarus' Iron Stay", 'Belt', 3, 25, ((43, 0, 20), (7, 0, 20 * 256)), ('Cold Resist +20%',)),
    Review(
        'Infernal Cranium', 'Cap', 5, 0, ((39, 0, 10), (41, 0, 10), (43, 0, 10), (45, 0, 10)), ('Fire Resist +10%',)
    ),
    Review(
        'Infernal Sign',
        'Heavy Belt',
        5,
        45,
        ((7, 0, 20 * 256),),
        (),
        'Infernal Tools',
        trade='trash',
        player_class='Necromancer',
    ),
    Review(
        'Infernal Torch',
        'Grim Wand',
        5,
        0,
        ((83, 2, 1),),
        ('Necromancer',),
        'Infernal Tools',
        player_class='Necromancer',
    ),
    Review("Iratha's Coil", 'Crown', 15, 55, ((39, 0, 30), (41, 0, 30)), ('Fire Resist +30%', 'Lightning Resist +30%')),
    Review(
        "Iratha's Collar",
        'Amulet',
        15,
        0,
        ((45, 0, 30), (110, 0, 75)),
        ('Poison Resist +30%',),
        "Iratha's Finery",
        leveling='high',
    ),
    Review("Iratha's Cord", 'Heavy Belt', 15, 45, ((21, 0, 5),), (), "Iratha's Finery", leveling='high'),
    Review(
        "Iratha's Cuff",
        'Light Gauntlets',
        15,
        45,
        ((43, 0, 30),),
        ('Cold Resist +30%',),
        "Iratha's Finery",
        leveling='high',
    ),
)


def condition(review):
    if review.combination == 'cow':
        return (
            "Use Cow King's Hooves, Cow King's Hide and Cow King's Horns together with Death's Hand and Death's Guard; "
            "the guide pairs these with Ancient's Pledge."
        )
    if review.combination == 'hsarus-boots':
        return (
            "Attack-rating set bonus requires a second Hsarus piece (for example Hsarus' Iron Stay). "
            'Movement and fire resistance are standalone.'
        )
    return (
        f'Requires a compatible {review.combination} combination; '
        'a single piece does not grant partial/full-set bonuses.'
    )


def cases(reviews=REVIEWS, *, prefix='survival-leveling-set'):
    for review in reviews:
        item = Item(review.base, 'set', review.name, review.stats)
        context = {
            'player_class': review.player_class,
            'player_level': review.level,
            'player_strength': review.strength,
            'player_dexterity': 0,
            'player_items': [],
        }
        variants = [
            ('equip-level', item, context, 'positive', 'met'),
            ('below-level', item, {**context, 'player_level': review.level - 1}, 'negative', 'unmet'),
            ('unknown-level', item, {k: v for k, v in context.items() if k != 'player_level'}, 'unknown', 'unknown'),
            ('unidentified', replace(item, identified=False), context, 'negative', None),
        ]
        if review.strength:
            variants.append(
                ('below-strength', item, {**context, 'player_strength': review.strength - 1}, 'negative', 'unmet')
            )
        for label, candidate, loadout, scenario, fit in variants:
            leveling = {
                'tier': review.leveling,
                'required_level': review.level,
                'requirements_fit': IsPartialDict(status=fit),
            }
            if review.combination:
                leveling.update(status='conditional', conditions=Contains(condition(review)))
            else:
                leveling.update(status='recommended', source=IsPartialDict(id='mrllamasc-transcript'))
            assessment = (
                IsPartialDict(
                    trade_tier=IsPartialDict(status='reviewed', tier=review.trade),
                    leveling=Contains(IsPartialDict(**leveling)),
                )
                if fit
                else IsPartialDict(leveling=[])
            )
            yield Case(
                id=f'{prefix}/{review.name}/{label}',
                item=candidate,
                context=loadout,
                scenario=scenario,
                covers=(f'named:set:{review.name}',),
                expected={'assessment': assessment, 'price_estimate': IsPartialDict(estimate_ist=None)},
                report_contains=(
                    review.name,
                    f'Trade tier: {review.trade}',
                    *(('Leveling: high',) if review.leveling == 'high' else ()),
                    *review.snippets,
                )
                if fit
                else (),
                report_absent=('Leveling: mid', 'Leveling: low')
                + (
                    ('Trade tier:', 'Leveling:')
                    if fit is None
                    else ('30% Increased Attack Speed', 'Cannot Be Frozen', 'Maximum Fire Resist')
                ),
                evidence=(
                    "third-parties/d2data/json/setitems.json:/Cow King's Hoofs"
                    if review.name == "Cow King's Hooves"
                    else f'third-parties/d2data/json/setitems.json:/{review.name}',
                    'third-parties/d2data/json/armor.json',
                    'third-parties/d2data/json/weapons.json',
                    'pricing/data/appraisal-recommendations.json',
                    f'pricing/knowledge/assessment/rules/named_leveling_reviews.json:set:{review.name}',
                    f'pricing/knowledge/assessment/rules/named_tier_reviews.json:set:{review.name}',
                ),
            )


CASES = tuple(cases())
