"""Potion defaults. Thresholds are percentages; trigger strictly below each value."""

PLAYER_HEALTH_POTION_BELOW_PERCENT = 65
PLAYER_REJUVENATION_BELOW_PERCENT = 40
MERC_HEALTH_POTION_BELOW_PERCENT = 55
MERC_REJUVENATION_BELOW_PERCENT = 20

# Cooldowns count from the last potion sent, shared across OSD instances.
POTION_COOLDOWN_SECONDS = 3.0
PLAYER_REJUVENATION_COOLDOWN_SECONDS = 1.0
SAMPLE_MAX_AGE_SECONDS = 1.0
CONSUMPTION_TIMEOUT_SECONDS = 2.0
